BoxLayout:
    orientation: "vertical"

    BoxLayout:
        orientation: "horizontal"

        TextInput:
            id: input_miles
            text: "0"

        BoxLayout:
            orientation: "vertical"
            Button:
                text: "Up"
                on_press: app.handle_increment(1)

            Button:
                text: "Down"
                on_press: app.handle_increment(-1)

    Button:
        text: "Convert miles to km"
        on_press: app.convert()

    Label:
        id: output_km
        text: root.output_text
        color: (1, 1, 0, 1)